export default [
    'Aracaju',
    'Barra dos Coqueiros',
    'Laranjeiras',
    'Nossa Senhora do Socorro',
    'São Cristóvão',
    'Areia Branca',
    'Campo do Brito',
    'Carira',
    'Frei Paulo',
    'Itabaiana',
    'Macambira',
    'Malhador',
    'Moita Bonita',
    'Pedra Mole',
    'Pinhão',
    'Ribeirópolis',
    'São Domingos',
    'Lagarto',
    'Poço Verde',
    'Riachão do Dantas',
    'Simão Dias',
    'Tobias Barreto',
    'Boquim',
    'Estância',
    'Indiaroba',
    'Itabaianinha',
    'Pedrinhas',
    'Salgado',
    'Santa Luzia do Itanhy',
    'Tomar do Geru',
    'Umbaúba',
    'Canindé de São Francisco',
    'Gararu',
    'Monte Alegre de Sergipe',
    'Nossa Senhora da Glória',
    'Nossa Senhora de Lourdes',
    'Poço Redondo',
    'Porto da Folha',
    'Amparo de São Francisco',
    'Aquidabã',
    'Canhoba',
    'Cedro de São João',
    'Ilha das Flores',
    'Japoatã',
    'Malhada dos Bois',
    'Muribeca',
    'Neópolis',
    'Pacatuba',
    'Propriá',
    'Santana do São Francisco',
    'São Francisco',
    'Telha',
    'Aparecida',
    'Graccho Cardoso',
    'Itabi',
    'Capela',
    'Divina Pastora',
    'Riachuelo',
    'Santa Rosa de Lima',
    'Rosário do Catete',
    'Siriri',
    'Brejo Grande',
    'Pirambu',
    'Santo Amaro das Brotas',
    'Itaporanga d\'Ajuda',
    'Maruim'
]